import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, Download, BookOpen, Check, X, Award, RotateCcw } from 'lucide-react';
import pptxgen from 'pptxgenjs';

export default function RemedialPresentation({ content, onClose }) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [answers, setAnswers] = useState({}); // { questionIndex: optionIndex }
  const [submitted, setSubmitted] = useState({}); // { questionIndex: true }
  
  // Format content to guarantee slides lists
  const data = {
    title: content.title || `${content.topic} Simplified`,
    topic: content.topic,
    student_name: content.student_name || 'Student',
    slides: content.slides || [],
    worked_example: content.worked_example || null,
    practice_questions: content.practice_questions || content.practice_questions_list || []
  };

  const totalSlides = data.slides.length + (data.worked_example ? 1 : 0) + (data.practice_questions.length > 0 ? 1 : 0);

  const handleNext = () => {
    if (currentSlide < totalSlides - 1) {
      setCurrentSlide(currentSlide + 1);
    }
  };

  const handleBack = () => {
    if (currentSlide > 0) {
      setCurrentSlide(currentSlide - 1);
    }
  };

  const handleSelectOption = (qIdx, optIdx) => {
    if (submitted[qIdx]) return;
    setAnswers({ ...answers, [qIdx]: optIdx });
  };

  const handleSubmitQuestion = (qIdx) => {
    if (answers[qIdx] === undefined) return;
    setSubmitted({ ...submitted, [qIdx]: true });
  };

  const handleResetQuiz = () => {
    setAnswers({});
    setSubmitted({});
  };

  // Compile PPTX using pptxgenjs client-side
  const handleDownloadPPTX = () => {
    try {
      const pptx = new pptxgen();
      pptx.layout = 'LAYOUT_16X9';
      
      // Slide Theme Colors (Dark Slate + Indigo Accent)
      const bgColor = '0B0F19';
      const headingColor = '6366F1';
      const textColor = 'F1F5F9';
      
      // 1. Cover Slide
      const slide1 = pptx.addSlide();
      slide1.background = { fill: bgColor };
      slide1.addText(data.title.toUpperCase(), {
        x: 0.5, y: 2.0, w: '90%', h: 1.5,
        fontSize: 36, bold: true, color: headingColor, align: 'center'
      });
      slide1.addText(`Personalized Remedial Learning Deck\nTopic: ${data.topic} | Student: ${data.student_name}`, {
        x: 0.5, y: 3.6, w: '90%', h: 1.0,
        fontSize: 18, color: textColor, align: 'center'
      });
      slide1.addText("Generated by SmartClass AI", {
        x: 0.5, y: 5.8, w: '90%', h: 0.5,
        fontSize: 11, color: '64748B', align: 'center', italic: true
      });

      // 2. Body Slides
      data.slides.forEach((s) => {
        const slide = pptx.addSlide();
        slide.background = { fill: bgColor };
        
        // Header
        slide.addText(s.title, {
          x: 0.5, y: 0.5, w: '90%', h: 0.8,
          fontSize: 26, bold: true, color: headingColor
        });
        
        // Bullets
        const bulletsText = s.bullets.map(b => ({ 
          text: `  ${b}\n\n`, 
          options: { bullet: true, color: textColor, fontSize: 16 } 
        }));
        
        slide.addText(bulletsText, {
          x: 0.5, y: 1.5, w: '90%', h: 3.3
        });
        
        // Analogy
        if (s.analogy) {
          slide.addText(`💡 ANALOGY:\n${s.analogy}`, {
            x: 0.5, y: 5.0, w: '90%', h: 1.3,
            fontSize: 13, color: 'C084FC', italic: true,
            fill: { fill: '1E1B4B' },
            margin: 10
          });
        }
      });

      // 3. Worked Example Slide
      if (data.worked_example) {
        const slideEx = pptx.addSlide();
        slideEx.background = { fill: bgColor };
        
        slideEx.addText("Worked Example step-by-step", {
          x: 0.5, y: 0.5, w: '90%', h: 0.8,
          fontSize: 26, bold: true, color: headingColor
        });
        
        slideEx.addText(`Problem Statement:\n${data.worked_example.problem}`, {
          x: 0.5, y: 1.3, w: '90%', h: 1.0,
          fontSize: 16, bold: true, color: textColor,
          fill: { fill: '1E293B' }, margin: 8
        });

        const stepsText = data.worked_example.steps.map(step => ({ 
          text: `  ${step}\n`, 
          options: { bullet: true, color: textColor, fontSize: 13 } 
        }));

        slideEx.addText(stepsText, {
          x: 0.5, y: 2.5, w: '90%', h: 2.8
        });
        
        slideEx.addText(`Final Answer: ${data.worked_example.final_solution}`, {
          x: 0.5, y: 5.6, w: '90%', h: 0.8,
          fontSize: 18, bold: true, color: '34D399'
        });
      }

      // 4. Practice Questions
      if (data.practice_questions && data.practice_questions.length > 0) {
        data.practice_questions.forEach((q, idx) => {
          const slideQ = pptx.addSlide();
          slideQ.background = { fill: bgColor };
          
          slideQ.addText(`Extra Practice Question ${idx + 1}`, {
            x: 0.5, y: 0.5, w: '90%', h: 0.8,
            fontSize: 26, bold: true, color: headingColor
          });
          
          slideQ.addText(q.question, {
            x: 0.5, y: 1.3, w: '90%', h: 1.0,
            fontSize: 16, color: textColor
          });

          const optionsText = q.options.map((opt, oIdx) => {
            const letter = String.fromCharCode(65 + oIdx);
            return { text: `  ${letter}. ${opt}\n`, options: { color: 'CBD5E1', fontSize: 14 } };
          });
          
          slideQ.addText(optionsText, {
            x: 0.5, y: 2.5, w: '90%', h: 2.5
          });

          slideQ.addText(`Answer Key: Option ${q.answer}\nExplanation: ${q.explanation}`, {
            x: 0.5, y: 5.3, w: '90%', h: 1.0,
            fontSize: 11, color: '94A3B8', italic: true
          });
        });
      }

      // Download file
      const fileName = `SmartClass-${data.topic.replace(/\s+/g, '-')}-${data.student_name.replace(/\s+/g, '-')}.pptx`;
      pptx.writeFile({ fileName });
    } catch (e) {
      console.error('PPTX export error:', e);
      alert('Failed to export PPTX. You can review the slides directly in-app!');
    }
  };

  const getSlideIndexDetails = () => {
    // 0 to slides.length - 1: normal slides
    // slides.length: Worked example (if exists)
    // slides.length + 1 (or slides.length if no worked example): Quiz
    let type = 'slide';
    let localIdx = currentSlide;

    if (currentSlide < data.slides.length) {
      type = 'slide';
      localIdx = currentSlide;
    } else if (data.worked_example && currentSlide === data.slides.length) {
      type = 'worked_example';
    } else {
      type = 'quiz';
    }

    return { type, localIdx };
  };

  const { type, localIdx } = getSlideIndexDetails();

  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-slate-950 text-slate-100 overflow-hidden">
      {/* Header bar */}
      <div className="flex justify-between items-center py-4 px-6 border-b border-slate-800 bg-slate-900/60 backdrop-blur-md">
        <div className="flex items-center gap-3">
          <BookOpen className="h-6 w-6 text-indigo-400" />
          <div>
            <h1 className="font-bold text-lg text-white">{data.title}</h1>
            <p className="text-xs text-slate-400">Personalized Learning for: <span className="text-indigo-300 font-semibold">{data.student_name}</span> | Topic: <span className="text-violet-300 font-semibold">{data.topic}</span></p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleDownloadPPTX}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 rounded-xl text-xs font-semibold cursor-pointer active:scale-95 transition-all text-white shadow-md shadow-indigo-600/10"
          >
            <Download className="h-4 w-4" />
            Download PPTX
          </button>
          
          <button
            onClick={onClose}
            className="px-4 py-2 border border-slate-800 hover:bg-slate-800 rounded-xl text-xs font-semibold cursor-pointer transition-colors"
          >
            Exit Viewer
          </button>
        </div>
      </div>

      {/* Main Slide Container */}
      <div className="flex-1 flex items-center justify-center p-6 md:p-12 relative overflow-y-auto">
        <div className="w-full max-w-4xl min-h-[500px] glass-panel rounded-3xl p-8 md:p-12 flex flex-col justify-between shadow-2xl relative border border-slate-800">
          
          {/* Cover / Title Slide Rendering */}
          {type === 'slide' && data.slides[localIdx] && (
            <div className="flex-1 flex flex-col justify-center animate-fadeIn duration-300">
              <span className="text-xs font-bold text-indigo-400 uppercase tracking-widest mb-2 block">Concept Study</span>
              <h2 className="text-3xl md:text-4xl font-extrabold text-white mb-6 border-b border-indigo-500/20 pb-4">
                {data.slides[localIdx].title}
              </h2>
              
              <div className="space-y-4 flex-1">
                {data.slides[localIdx].bullets.map((bullet, bIdx) => (
                  <div key={bIdx} className="flex items-start gap-3 text-slate-200 text-base md:text-lg leading-relaxed">
                    <span className="h-2 w-2 rounded-full bg-indigo-500 mt-2.5 shrink-0" />
                    <p>{bullet}</p>
                  </div>
                ))}
              </div>

              {data.slides[localIdx].analogy && (
                <div className="mt-8 p-4 bg-indigo-950/40 border border-indigo-900/30 rounded-2xl flex gap-3.5 items-start">
                  <span className="text-xl shrink-0 mt-0.5">💡</span>
                  <div>
                    <span className="text-xs font-bold text-indigo-400 uppercase tracking-wider block mb-1">Simple Analogy</span>
                    <p className="text-slate-300 text-sm italic">{data.slides[localIdx].analogy}</p>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Worked Example Slide Rendering */}
          {type === 'worked_example' && data.worked_example && (
            <div className="flex-1 flex flex-col justify-center animate-fadeIn duration-300">
              <span className="text-xs font-bold text-emerald-400 uppercase tracking-widest mb-2 block">Step-By-Step Example</span>
              <h2 className="text-3xl font-extrabold text-white mb-5 border-b border-slate-800 pb-3">
                Let's Walk Through One
              </h2>

              <div className="p-4 bg-slate-900/60 border border-slate-800 rounded-2xl mb-6 shadow-inner">
                <span className="text-xs font-semibold text-slate-400 block mb-1">PROBLEM:</span>
                <p className="text-base md:text-lg font-bold text-indigo-300 whitespace-pre-wrap">{data.worked_example.problem}</p>
              </div>

              <div className="space-y-3.5 mb-6 flex-1">
                {data.worked_example.steps.map((step, sIdx) => (
                  <div key={sIdx} className="flex gap-3 text-slate-300 text-sm md:text-base leading-relaxed">
                    <span className="flex items-center justify-center h-6 w-6 rounded-full bg-slate-800 text-xs font-bold text-slate-400 shrink-0 mt-0.5 border border-slate-700">
                      {sIdx + 1}
                    </span>
                    <p className="whitespace-pre-wrap">{step}</p>
                  </div>
                ))}
              </div>

              <div className="p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-2xl flex items-center justify-between">
                <div>
                  <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider block">FINAL SOLUTION</span>
                  <p className="text-emerald-300 text-lg font-extrabold">{data.worked_example.final_solution}</p>
                </div>
                <div className="p-2.5 bg-emerald-500/20 rounded-full">
                  <Check className="h-6 w-6 text-emerald-400" />
                </div>
              </div>
            </div>
          )}

          {/* Practice Quiz Slide Rendering */}
          {type === 'quiz' && (
            <div className="flex-1 flex flex-col justify-center animate-fadeIn duration-300">
              <div className="flex items-center justify-between border-b border-slate-800 pb-3 mb-5">
                <div>
                  <span className="text-xs font-bold text-violet-400 uppercase tracking-widest block">Check Your Understanding</span>
                  <h2 className="text-3xl font-extrabold text-white">Extra Practice Questions</h2>
                </div>
                <button
                  onClick={handleResetQuiz}
                  className="flex items-center gap-1.5 px-3 py-1.5 border border-slate-800 rounded-lg text-xs text-slate-400 hover:text-slate-200 hover:bg-slate-900 cursor-pointer active:scale-95 transition-all"
                >
                  <RotateCcw className="h-3 w-3" />
                  Retry
                </button>
              </div>

              <div className="space-y-6 overflow-y-auto max-h-[380px] pr-2">
                {data.practice_questions.map((q, qIdx) => {
                  const selectedOpt = answers[qIdx];
                  const isSubmitted = submitted[qIdx];
                  const answerLetter = q.answer;
                  const correctOptIdx = answerLetter.charCodeAt(0) - 65; // 'A'->0, 'B'->1

                  return (
                    <div key={qIdx} className="p-5 bg-slate-900/40 border border-slate-800/80 rounded-2xl space-y-4">
                      <div className="flex items-start gap-2.5">
                        <span className="bg-indigo-900/40 border border-indigo-500/20 text-indigo-300 text-xs font-bold px-2 py-0.5 rounded-md mt-0.5">Q{qIdx + 1}</span>
                        <h3 className="text-sm font-semibold text-white leading-relaxed">{q.question}</h3>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
                        {q.options.map((opt, oIdx) => {
                          const optionLetter = String.fromCharCode(65 + oIdx);
                          const isSelected = selectedOpt === oIdx;
                          const isCorrectOpt = oIdx === correctOptIdx;

                          let btnStyle = "border-slate-800 bg-slate-950/50 hover:bg-slate-900 text-slate-300";
                          if (isSelected) {
                            btnStyle = "border-indigo-500 bg-indigo-500/10 text-indigo-300 font-medium";
                          }
                          if (isSubmitted) {
                            if (isCorrectOpt) {
                              btnStyle = "border-emerald-500 bg-emerald-500/10 text-emerald-300 font-semibold";
                            } else if (isSelected) {
                              btnStyle = "border-rose-500 bg-rose-500/10 text-rose-300 font-medium";
                            } else {
                              btnStyle = "border-slate-850 bg-slate-950/20 text-slate-500 opacity-60";
                            }
                          }

                          return (
                            <button
                              key={oIdx}
                              type="button"
                              onClick={() => handleSelectOption(qIdx, oIdx)}
                              disabled={isSubmitted}
                              className={`w-full p-3 text-left text-xs rounded-xl border flex items-center justify-between transition-all cursor-pointer ${btnStyle}`}
                            >
                              <span><strong className="mr-1">{optionLetter}.</strong> {opt}</span>
                              {isSubmitted && isCorrectOpt && <Check className="h-4.5 w-4.5 text-emerald-400 shrink-0" />}
                              {isSubmitted && isSelected && !isCorrectOpt && <X className="h-4.5 w-4.5 text-rose-400 shrink-0" />}
                            </button>
                          );
                        })}
                      </div>

                      {!isSubmitted ? (
                        <button
                          type="button"
                          onClick={() => handleSubmitQuestion(qIdx)}
                          disabled={selectedOpt === undefined}
                          className="px-4 py-2 bg-slate-800 hover:bg-indigo-600 disabled:bg-slate-900 disabled:opacity-40 disabled:text-slate-600 text-white text-xs font-semibold rounded-lg transition-colors cursor-pointer"
                        >
                          Check Answer
                        </button>
                      ) : (
                        <div className="p-3.5 bg-slate-950/60 border-l-2 border-indigo-500 rounded-r-xl text-[11px] leading-relaxed text-slate-400 italic">
                          <strong className="text-slate-300 block not-italic mb-0.5">Explanation:</strong>
                          {q.explanation}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Progress / Navigation row */}
          <div className="mt-8 border-t border-slate-800/80 pt-6 flex items-center justify-between">
            <span className="text-xs font-medium text-slate-500">
              Slide {currentSlide + 1} of {totalSlides}
            </span>

            {/* Indicator dots */}
            <div className="hidden sm:flex items-center gap-1.5">
              {Array.from({ length: totalSlides }).map((_, idx) => (
                <div
                  key={idx}
                  className={`h-1.5 rounded-full transition-all duration-300 ${
                    currentSlide === idx ? 'w-6 bg-indigo-500' : 'w-1.5 bg-slate-800'
                  }`}
                />
              ))}
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleBack}
                disabled={currentSlide === 0}
                className="p-2 border border-slate-800 rounded-xl bg-slate-900/60 text-slate-300 hover:text-white hover:bg-slate-800 disabled:opacity-40 cursor-pointer active:scale-95 transition-all"
              >
                <ArrowLeft className="h-4 w-4" />
              </button>

              <button
                onClick={handleNext}
                disabled={currentSlide === totalSlides - 1}
                className="p-2 border border-slate-800 rounded-xl bg-slate-900/60 text-slate-300 hover:text-white hover:bg-slate-800 disabled:opacity-40 cursor-pointer active:scale-95 transition-all"
              >
                <ArrowRight className="h-4 w-4" />
              </button>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
